### PR TITLE
Update CMakeLists.txt fix include path

### PR DESCRIPTION
**Pull request by jiayuehua**

### CODE REVIEW

**Comment by jiayuehua** [comment]
@foonathan

**Comment by foonathan** [comment]
Can you elaborate on the consequences and reason for this change?

**Comment by jiayuehua** [comment]
If installed to include/foonathan, then client code must use
"include/foonathan/foonathan/memory…" other than "include/foonathan/memory". 

after this fix, some other vcpkg port that already rely on your memory lib can work again.

**Comment by foonathan** [comment]
Okay, that's fair. Thanks.

**Pull request merged**
